### ISSUE TITLE
Config utilisateur, entity flag

### ISSUE THREAD

**Issue by t-geindre** [M6Web/DomainUserBundle#4]
D'après ce que je comprends dans le README :

``` yml
entities:
    article:
        active: true # Arbitrary flag you can use to filter your entities in your repositories
```

On devrait pouvoir mettre n'importe quel flag sous nos entités. Sauf que le check de cette configuration ne permet que _active_ ou _publication_ :

``` php
->arrayNode('entities')
    ->prototype('array')
        ->children()
            ->booleanNode('active')->end()
            ->booleanNode('publication')->end()
        ->end()
    ->end()
->end()
```

https://github.com/M6Web/DomainUserBundle/blob/master/User/UserConfiguration.php#L34
